### ISSUE TITLE
install -- ld returned 1 exit status

### ISSUE THREAD

**Issue by jaudall** [kjenike/Panagram#4]
ld not finding some options ...

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/376355/214430183-b5944eff-4fa5-479d-872a-32c3f337b6aa.png">

**Comment by jaudall** [comment]
My HPC support had the same issues:

"_I got the same errors. I've tried various combinations of python, gcc, build arguments, and even a newer version of Centos with no luck. If we find a work around I will keep you updated_"

**Comment by kjenike** [comment]
This looks like it is an issue with installing KMC? Are you able to successfully install KMC independently?

**Comment by jaudall** [comment]
> 

This KMC? 
https://anaconda.org/bioconda/kmc

It installed by conda, no problem. kmc and kmc-tools cmds work fine from the command line (now).

I deleted panagram, re-cloned it and tried to build it again. Same error. 

Would you please put a detection function in build script like there is for numpy etc.? Maybe that would get us around the issue altogether.

**Comment by kjenike** [comment]
Hello again! Sorry it took so long to get back to you. Could you try re-downloading and installing now? We've made some changes and I believe it should work now. We have tested on both Linux and Mac.

**Comment by jaudall** [comment]
Installed great! Thanks for the fix!
