### ISSUE TITLE
error during index step

### ISSUE THREAD

**Issue by jhumann** [kjenike/Panagram#6]
I have tried running panagram with my own genomes and the test data and got an error about invalid options for bgzip.  It looks like because of that error, some files are not being made.  Here is the stdout from the bacteria test data:

jhumann@compute2:~/Panagram_testData$ panagram index conf.toml
Stage 1: 100%
1st stage: 0.184879s
2nd stage: 1.23304s
Total    : 1.41792s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :      3171496
   No. of unique counted k-mers       :      3171496
   Total no. of k-mers                :      5601949
   Total no. of sequences             :            2
   Total no. of super-k-mers          :            0
in1: 100%
Stage 1: 100%
1st stage: 0.174545s
2nd stage: 0.855531s
Total    : 1.03008s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :      2848222
   No. of unique counted k-mers       :      2848222
   Total no. of k-mers                :      4641641
   Total no. of sequences             :            1
   Total no. of super-k-mers          :            0
in1: 100%
Stage 1: 100%
1st stage: 0.182817s
2nd stage: 1.41683s
Total    : 1.59965s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :      2973159
   No. of unique counted k-mers       :      2973159
   Total no. of k-mers                :      5682233
   Total no. of sequences             :            7
   Total no. of super-k-mers          :            0
in1: 100%
Stage 1: 100%
1st stage: 0.174789s
2nd stage: 1.37968s
Total    : 1.55447s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :      2881243
   No. of unique counted k-mers       :      2881243
   Total no. of k-mers                :      4801381
   Total no. of sequences             :            2
   Total no. of super-k-mers          :            0
in1: 100%
Stage 1: 100%
1st stage: 0.16727s
2nd stage: 0.6703s
Total    : 0.83757s
Tmp size : 0MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :      2796719
   No. of unique counted k-mers       :      2796719
   Total no. of k-mers                :      4828781
   Total no. of sequences             :            2
   Total no. of super-k-mers          :            0
in1: 100%
in1: 100% in2: 100% in3: 100% in4: 100% in5: 100%
Anchored NZ_CP015023.1
Anchored NZ_CP015022.1
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
Anchored ecoli
Anchored NC_000913.3
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
Anchored ecoli_K12
Anchored NC_016845.1
Anchored NC_016838.1
Anchored NC_016846.1
Anchored NC_016839.1
Anchored NC_016840.1
Anchored NC_016847.1
Anchored NC_016841.1
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
Anchored klebsiella
Anchored NZ_CP065890.1
Anchored NZ_CP065891.1
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
Anchored salmonella
Anchored NC_004337.2
Anchored NC_004851.1
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
bgzip: invalid option -- 'r'
bgzip: invalid option -- 'I'
Anchored shigella
Traceback (most recent call last):
  File "/u/jhumann/.local/bin/panagram", line 8, in <module>
    sys.exit(main())
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/__main__.py", line 122, in main
    args.main.run()
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/__main__.py", line 107, in run
    return self.cmd.run()
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/index.py", line 106, in run
    self.write()#args)
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/index.py", line 309, in write
    self.bitmaps = {
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/index.py", line 310, in <dictcomp>
    name : KmerBitmap(self.params, name, "r", self.chrs) for name in self.genomes
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/index.py", line 594, in __init__
    self._init_read()
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/index.py", line 623, in _init_read
    self.blocks = {s : self.load_bgz_blocks(self.idx_fname(s)) for s in self.steps}
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/index.py", line 623, in <dictcomp>
    self.blocks = {s : self.load_bgz_blocks(self.idx_fname(s)) for s in self.steps}
  File "/u/jhumann/.local/lib/python3.10/site-packages/panagram/index.py", line 634, in load_bgz_blocks
    idx_in = open(fname, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './anchors/ecoli.1.gzi'

**Comment by skovaka** [comment]
Hmm, this could be an issue with your bgzip version. From the example directory, can you try running this command: `bgzip -r anchors/ecoli.1.bgz -I anchors/ecoli.1.gzi`

I expect that to return the same error that you saw. Can you also send me the output of `bgzip -h`? If you don't see the `-r, --reindex` and `-I, --index-name` options, then you probably need to update to the latest version of bgzip. Let me know and I can update to specify a version number.

**Comment by jhumann** [comment]
Okay, we have samtools 1.16.1 installed and it does have those options.  And I noticed in the command you provided that the first file doesn't exist.  Here is the command I ran and it appeared to run (output a file of 1000 b): 

`bgzip -r anchors/ecoli.1.bgz.gz -I anchors/ecoli.1.gzi`

I don't have a 'ecoli.1.bgz' in my anchors folder, I only have 'ecoli.1.bgz.gz'

**Comment by skovaka** [comment]
Very weird. Could you share which OS you're using? One thing you could try is change [line 759](https://github.com/kjenike/panagram/blob/main/panagram/index.py#L759) to `"bgzip", "-r", "-I", self.idx_fname(step), self.bgz_fname(step)])` (i.e. move the 2nd parameter to the end), and then re-install and re-run the example data. 

If that does not work, you could comment out lines 757-759 and re-install and re-run. That will certainly fail to run, but I'm curious if you then only see files ending in ".bgz", not ".bgz.gz". There shouldn't be any files ending in ".bgz.gz", so I'm guessing those lines are for some reason double-compressing rather than indexing as they should.

**Comment by jhumann** [comment]
The OS is Ubuntu 20.04.  I will try the suggestions and get back to you!

**Comment by jhumann** [comment]
Okay, I changed line 759 as you suggested and got the same "r" and "I" not being valid options, and "[bgzip] No such file or directory: ./anchors/ecoli.1.gzi" 

Complete stdout in file:
[line759changeErrors.txt](https://github.com/kjenike/panagram/files/10688368/line759changeErrors.txt)

When I look in the anchors directory, I only see 'ecoli.100.bgz' and 'ecoli.1.bgz'.  Previously I saw files for all the genomes, but they were '.bgz.gz'

**Comment by jhumann** [comment]
When I comment out lines 757-759, I only get '.bgz' files in the anchors directory as expected.

**Comment by jhumann** [comment]
Any other ideas on how to resolve this?

**Comment by skovaka** [comment]
Sorry for the delay, I just pushed a few changes which may have fixed your issue. If not, just to be sure, can send me the output `bgzip --version`? bgzip is technically part of htslib, not samtools, so it's possible the versions are different. I just tested with the latest bgzip version (1.17) and it worked.

**Comment by jhumann** [comment]
Yeah, we needed to update htslib.  It's working fine now.  Thanks!
